export const GET_NEWS_API_SOURCES = "GET_NEWS_API_SOURCES";
export const GET_NEWS_API_SOURCES_SUCCESS = "GET_NEWS_API_SOURCES_SUCCESS";
export const GET_NEWS_API_SOURCES_FAILURE = "GET_NEWS_API_SOURCES_FAILURE";


export const GET_NEWS_API_ARTICLES = "GET_NEWS_API_ARTICLES";
export const GET_NEWS_API_ARTICLES_SUCCESS = "GET_NEWS_API_ARTICLES_SUCCESS";
export const GET_NEWS_API_ARTICLES_FAILURE = "GET_NEWS_API_ARTICLES_FAILURE";