export const GET_NY_TIMES_ARTICLES = "GET_NY_TIMES_ARTICLES";
export const GET_NY_TIMES_ARTICLES_SUCCESS = "GET_NY_TIMES_ARTICLES_SUCCESS";
export const GET_NY_TIMES_ARTICLES_FAILURE = "GET_NY_TIMES_ARTICLES_FAILURE";