export const GET_THE_GUARDIAN_SOURCES = "GET_THE_GUARDIAN_SOURCES";
export const GET_THE_GUARDIAN_SOURCES_SUCCESS = "GET_THE_GUARDIAN_SOURCES_SUCCESS";
export const GET_THE_GUARDIAN_SOURCES_FAILURE = "GET_THE_GUARDIAN_SOURCES_FAILURE";


export const GET_THE_GUARDIAN_ARTICLES = "GET_THE_GUARDIAN_ARTICLES";
export const GET_THE_GUARDIAN_ARTICLES_SUCCESS = "GET_THE_GUARDIAN_ARTICLES_SUCCESS";
export const GET_THE_GUARDIAN_ARTICLES_FAILURE = "GET_THE_GUARDIAN_ARTICLES_FAILURE";